CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_A
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_B
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_C
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_D
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_E
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_F
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_G
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_H
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_I
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_J
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);



CREATE TABLE BSSDATA.OFR_ASSET_INST_STAT_HIST_K
     (
      Instant_Row_Id VARCHAR(15) TITLE '即买即通唯一编号',
      Start_Dt DATE FORMAT 'YYYYMMDD' TITLE '开始时间',
      End_Dt DATE FORMAT 'YYYYMMDD' TITLE '结束时间',
      Asset_Row_Id VARCHAR(15) TITLE '资产唯一编号',
      Asset_Integ_Id VARCHAR(30) TITLE '资产集成编号',
      Last_Upd_Dt DATE FORMAT 'YYYYMMDD' TITLE '最后一次更新时间',
      Instant_Sim VARCHAR(100) TITLE '即买即通SIM卡卡号',
      Instant_Nbr VARCHAR(100) TITLE '即买即通电话号码',
      Instant_Flg DECIMAL(22,0) TITLE '即买即通订单补录标志位',
      Stat_Name VARCHAR(50) TITLE '即买即通号码状态',
      Agent_Point_Id VARCHAR(30) TITLE '代理商网点编号',
      Agent_Point_Name VARCHAR(100) TITLE '代理商网点名称',
      Order_Row_Id VARCHAR(30) TITLE '订单头唯一编号',
      Latn_Id DECIMAL(2,0) TITLE 'ETL时间',
      Create_Dt DATE FORMAT 'YYYYMMDD' TITLE '本地网编号')
PRIMARY INDEX ( Instant_Row_Id )
PARTITION BY RANGE_N(End_Dt  BETWEEN DATE '2011-01-01' AND DATE '2014-12-31' EACH INTERVAL '10' YEAR ,
DATE '2015-01-01' AND DATE '2020-12-31' EACH INTERVAL '1' MONTH ,
DATE '3000-12-31' AND DATE '3000-12-31' EACH INTERVAL '1' DAY ,
 NO RANGE);




 CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_B
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_C
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);

CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_D
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_E
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_F
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_G
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_H
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_I
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_J
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
CREATE TABLE ZJBIC.OFR_MAIN_ASSET_CUR_K
(
    Asset_Row_Id varchar(15),
    Date_Cd date,
    Std_Prd_Lvl4_Name char(25),
    Std_User_Type_Lvl2_Name char(15),
    CPrd_Name char(20),
    Stat_Name char(6),
    Exch_Name varchar(50),
    Area_Name varchar(100),
    Area_Merge_Name varchar(200),
    Area_Type_Name char(10),
    Serv_Type_Name char(10),
    Telecom_Area_Name varchar(30),
    Accs_Nbr varchar(30),
    Circ_Nbr varchar(30),
    DATA_User_name varchar(30),
    Centrex_Grp_Id varchar(30),
    Vpn_Grp_Id varchar(30),
    Vpn_Inner_Id varchar(30),
    Wac_Grp_Id varchar(30),
    City_Type_Name char(8),
    User_Name varchar(100),
    Linkman_Name varchar(75),
    Link_Phone_Nbr varchar(100),
    Addr_Bunch_Name varchar(100),
    Addr_Name varchar(200),
    Std_Prd_Lvl4_Id int,
    Std_User_Type_Lvl2_Cd int,
    Cprd_Id char(12),
    Exch_Id varchar(50),
    Area_Id numeric(9,0),
    Telecom_Area_Id int,
    Asset_Integ_Id varchar(30),
    CCust_Id varchar(30),
    CCust_Row_Id varchar(15),
    CAcct_Row_Id varchar(15),
    Mkt_Channel_Name char(50),
    Mkt_Channel_Sub_Name char(100),
    MKt_Channel_Lvl2_Name char(8),
    Initiative_Suspend_Flg int,
    Peccancy_Suspend_Flg int,
    Loss_Suspend_Flg int,
    Owe_Suspend_Name char(4),
    Serv_Start_Dt date,
    Serv_End_Dt date,
    Free_Flg int,
    Corp_Pay_Flg int,
    Test_Flg int,
    No_Suspend_Flg int,
    No_Remind_Flg int,
    No_Call_Flg int,
    ZWXNW_Type_Name char(8),
    On_Serv_Flg int,
    Discon_Reason varchar(100),
    User_Grade char(8),
    Pre_Active_Status char(60),
    Fj_Area_Id numeric(9,0),
    Fj_Area_Name varchar(50),
    Zj_Area_Id numeric(9,0),
    Zj_Area_Name varchar(50),
    Last_Display_Area_Id numeric(9,0),
    Last_Display_Area_Name varchar(50),
    Asset_Id varchar(30),
    Depend_Circ_Nbr varchar(30),
    Line_Nbr varchar(30),
    Br_Exch_Id varchar(30),
    Dept_Row_Id varchar(15),
    Dept_Name varchar(100),
    Agent_Id varchar(15),
    Prom_Asset_Integ_Id varchar(30),
    Related_Asset_Integ_Id varchar(30),
    XNW_Type_Name char(25),
    Oneway_Stop_Dt date,
    Twoway_Stop_Dt date,
    Comb_Stat_Name char(8),
    Corp_User_Name char(8),
    Sales_Org_Lvl3_Cd char(5),
    Location_Attr char(5),
    Indus_Lvl3_Id char(5),
    CCust_Stat_Name char(6),
    Pay_Mode_Cd int,
    CCust_Cd varchar(30),
    Manager_Id numeric(15,0),
    Manager_Name varchar(30),
    Manager_Rel_Nbr varchar(40),
    S_Manager_Id numeric(15,0),
    Cust_Manager_Id numeric(15,0),
    Vip_Manager_Id numeric(15,0),
    Vip_Manager_Name varchar(100),
    Vip_Manager_Rel_Nbr varchar(40),
    Bil_Flg int,
    On_Net_Flg int,
    Speed char(30),
    Centrex_Inner_Id varchar(30),
    Latn_Id int,
    Agent_Point_Name varchar(100),
    Shanxun_Flg int,
    Point_Type_Name varchar(30),
    Tyzh_Flg int,
    Vip_Ccust_Id varchar(30),
    Sales_Channel_Lvl3_Name varchar(30),
    Mkt_Channel_Lvl3_Name varchar(30),
    Out_Net_Type varchar(50),
    Out_Net_Dt date,
    Sales_Channel_Lvl2_Name varchar(30),
    Mkt_Employee_Id varchar(20),
    Mkt_Employee_Name varchar(100),
    Channel_Lvl1_Name_2014 varchar(100),
    Channel_Lvl2_Name_2014 varchar(100),
    Channel_Lvl3_Name_2014 varchar(100),
    Channel_Fin_Rpt_TYPE varchar(50),
    Channel_Dept_Name_2014 varchar(50),
    STAT_CHANGE_DT date,
    LOT_FLG int
);
