-----KPI_1.KPI_ASSET_FLG_A/C/D/F/G---------------------------------------------------------------------------------------------------------------
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_0001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_1001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_2001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_3001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_4001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_5001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_6001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_7001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_8001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_FLG_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_FLG_A_9001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;

INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_C_1 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_D_1 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_F_1 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_G_1 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;

-----Select * from KPI_1.KPI_ASSET_FLG_A_2;

INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_A_2 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_C_2 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_D_2 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_F_2 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_FLG_G_2 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;

-----Select * from KPI_2.KPI_ASSET_FLG_A_3;

INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_A_3 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_C_3 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_D_3 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_F_3 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_G_3 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;

-----Select * from KPI_2.KPI_ASSET_FLG_A_4;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_A_4 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_C_4 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_D_4 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_F_4 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_FLG_G_4 SELECT * FROM KPI_1.KPI_ASSET_FLG_A_1;


-----KPI_1.KPI_ASSET_IO_A/C/D/F/G-------------------------------------------------------------------------------------------------------------

COPY KPI_1.KPI_ASSET_IO_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_IO_A_0001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_IO_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_IO_A_1001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_IO_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_IO_A_2001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_IO_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_IO_A_3001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_IO_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_IO_A_4001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_IO_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_IO_A_5001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;

INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_C_1 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_D_1 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_F_1 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_G_1 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;

-----Select * from KPI_1.KPI_ASSET_IO_A_2;

INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_A_2 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_C_2 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_D_2 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_F_2 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_IO_G_2 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;

-----Select * from KPI_2.KPI_ASSET_IO_A_3;

INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_A_3 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_C_3 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_D_3 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_F_3 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_G_3 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;

-----Select * from KPI_2.KPI_ASSET_IO_A_4;

INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_A_4 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_C_4 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_D_4 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_F_4 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_IO_G_4 SELECT * FROM KPI_1.KPI_ASSET_IO_A_1;


-----KPI_1.KPI_ASSET_IO_A/C/D/F/G-------------------------------------------------------------------------------------------------------------

COPY KPI_1.KPI_ASSET_TER_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_TER_A_0001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_TER_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_TER_A_1001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_TER_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_TER_A_2001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_TER_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_TER_A_3001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_TER_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_TER_A_4001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_TER_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_TER_A_5001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY KPI_1.KPI_ASSET_TER_A_1 FROM '/data/SOURCE/biz_data2/KPI_KPI_ASSET_TER_A_6001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;


INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_C_1 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_D_1 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_F_1 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_G_1 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;

-----Select * from KPI_1.KPI_ASSET_TER_A_2;

INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_A_2 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_C_2 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_D_2 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_F_2 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_1.KPI_ASSET_TER_G_2 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;

-----Select * from KPI_2.KPI_ASSET_TER_A_3;

INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_A_3 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_C_3 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_D_3 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_F_3 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_G_3 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;

-----Select * from KPI_2.KPI_ASSET_TER_A_4;

INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_A_4 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_C_4 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_D_4 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_F_4 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;
INSERT /*+direct*/ INTO KPI_2.KPI_ASSET_TER_G_4 SELECT * FROM KPI_1.KPI_ASSET_TER_A_1;

-----ITFJYFX_1.DAPD_PRD_PO_INST_A/C/D/F/G-------------------------------------------------------------------------------------------------------------

COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_0001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_1001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_2001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_3001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_4001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_5001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_6001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_7001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_8001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_9001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;

COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_10001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_11001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_12001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_13001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_14001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_15001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_16001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_17001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_18001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_19001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;

COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_20001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_21001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_22001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_23001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_24001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_25001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_26001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_27001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_28001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;
COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_29001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;

COPY ITFJYFX_1.DAPD_PRD_PO_INST_A_1 FROM '/data/SOURCE/biz_data2/ITFJYFX_DAPD_PRD_PO_INST_A_30001.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10;

INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_C_1 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_D_1 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_F_1 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_G_1 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;

-----Select * from TFJYFX_1.DAPD_PRD_PO_INST_A_2;

INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_A_2 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_C_2 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_D_2 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_F_2 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_1.DAPD_PRD_PO_INST_G_2 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1

-----Select * from TFJYFX_2.DAPD_PRD_PO_INST_A_3;

INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_A_3 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_C_3 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_D_3 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_F_3 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_G_3 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;

-----Select * from TFJYFX_2.DAPD_PRD_PO_INST_A_4;

INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_A_4 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_C_4 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_D_4 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_F_4 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;
INSERT /*+direct*/ INTO ITFJYFX_2.DAPD_PRD_PO_INST_G_4 SELECT * FROM ITFJYFX_1.DAPD_PRD_PO_INST_A_1;