COPY ZJBIC.OFR_MAIN_ASSET_CUR_B FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_B_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_C FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_C_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_D FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_D_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_E FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_E_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_F FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_F_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_G FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_G_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_H FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_H_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_I FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_I_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_J FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_J_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY ZJBIC.OFR_MAIN_ASSET_CUR_K FROM '/data/SOURCE/biz_data3/OFR_MAIN_ASSET_CUR_K_20170731_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;




COPY BSSDATA.MKT_ASSET_CLAIM_A FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_A_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_B FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_B_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_C FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_C_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_D FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_D_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_E FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_E_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_F FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_F_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_G FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_G_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_H FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_H_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_I FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_I_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_G FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_G_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;
COPY BSSDATA.MKT_ASSET_CLAIM_K FROM '/data/SOURCE/biz_data2/BSSDATA_MKT_ASSET_CLAIM_K_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;


COPY BSSDATA.OFR_ASSET_EXI_HIST_A FROM '/data/SOURCE/biz_data2/BSSDATA_OFR_ASSET_EXI_HIST_A_*01.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;


COPY BSSDATA.OFR_MAIN_ASSET_HIST_A FROM '/data/SOURCE/biz_data3/BSSDATA_OFR_MAIN_ASSET_HIST_A_*01_T.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT REJECTMAX 10 NO ESCAPE  TRAILING NULLCOLS;


