COPY STAGE_1.OFR_PROM_BSI_HIST_Z FROM '/data/SOURCE/biz_data2/STAGE_OFR_PROM_BSI_HIST_Z_*1.dat' ON v_poc_node0002 DELIMITER E'\007' DIRECT RejectMax 10;

COPY STAGE_1.EVT_ORDI_HIST_A FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_A_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_B FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_B_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_C FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_C_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_D FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_D_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_E FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_E_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;

COPY STAGE_1.EVT_ORDI_HIST_F FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_F_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_G FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_G_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_H FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_H_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_I FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_I_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;
COPY STAGE_1.EVT_ORDI_HIST_J FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_J_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;

COPY STAGE_1.EVT_ORDI_HIST_K FROM '/data/SOURCE/business/biz_data3/STAGE_EVT_ORDI_HIST_K_*01_T.dat' ON any node DELIMITER E'\007' DIRECT RejectMax 10;