\timing 

SELECT
	--TOP 10*
	*
FROM (
	SELECT COUNT(P1.ASSET_ROW_ID) AS CNT
		,P1.CPL_DT
		,P1.AGENT_POINT_ID
	FROM KPI.KPI_ASSET_IO_A P1
	INNER JOIN DMN.CAG_COM_STD_PRD_LVL4 P2
		ON P1.STD_PRD_LVL4_ID = P2.STD_PRD_LVL4_ID
			AND P2.PRD_NAME = '宽带'
	WHERE P1.CPL_DT = DATE '2017-04-15'
		AND P1.IO_FLG = 'I'
		AND LAN_SPEED <> 'err'
	GROUP BY P1.CPL_DT
		,P1.AGENT_POINT_ID
	) X
ORDER BY CNT DESC LIMIT 10;

