\timing

SELECT COUNT(P1.ASSET_ROW_ID)
	,DATE_CD
FROM KPI.KPI_ASSET_FLG_A P1
INNER JOIN DMN.CAG_COM_STD_PRD_LVL4 P2
	ON P1.STD_PRD_LVL4_ID = P2.STD_PRD_LVL4_ID
		AND P2.PRD_NAME = 'CDMA'
WHERE P1.DATE_CD >= DATE '2017-04-15'
	AND P1.DATE_CD <= DATE '2017-04-19'
	AND P1.ON_NET_FLG = 1
GROUP BY DATE_CD;

